# pull the official base image
FROM mhart/alpine-node:12
# set working direction
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install application dependencies
COPY yarn.lock ./
COPY package.json ./
RUN npm i yarn --global && yarn install
# add app
COPY . ./
# start app
CMD ["yarn", "start"]