apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-application
  name: todolist-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi