apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-kub-todolist-1-12-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi