apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-password
  namespace: main-application
spec:
  encryptedData:
    DB_PASSWORD: AgAJCjbR+xpgaE1zEApSkvqjtTKOyIibgWSfsC5FUqyC/M+ukpicGJRBGx7BHMhlSBjAqAetB52/QSepN0NUumu4veLwNsNjAWxuFWPlcnFRgfSwmes3Udz8nWCtdbpdOrAhkK8HodqLSeoAYtFTgbqg+8TWuEZZLH21cbiOPdeGi/d/jgZaVY/isFbO7OUNpdAbruLjfa/sccbIqmvH/2qFL69SjiZjz/1lPHA4s9QeXYKoJetK8Ab2F6c7+ubnBlMAxivuP2C/KY9C7za/faL8b8r74V/+M2ngsbVolPH4s4x+U3eFSbiR7wE/1GaOla87yIQTvo3TEeNFonio1ByaDWkYysf4ynJsPwVRGwnwLAdYj6y1W+RdvapcYUifVzM0ib5ju6CgXUf+TA3jA0952DPGYobeC90BcZX4G9rJ18sxeHM4DkAnNslZ4v9SSSj1iLAmMXZSOhxnCcA8fTvfLi7p17WgxBeBktCmHb68v0RUr6Y0SVgWQCiPqmXVD/uDK7H5RPIhjwD+1e/63cUJr1sku9zAqY3wsSLex0N0vd7KKczB2wx4EFTR1kGeVSu/GsvoosOeAuj3Omlpz645fENWLxFFnidlVkVA49vE+3hjkMwrbD2WMs8b5LxyjY8REtjvuU6EWHjfhpkhUoDj8Fs5lw1axJfxLP3k6aTyJDNL6L4olqkPYpZL297pATrB405AY5G1Qno7XCDcW/neIAMnbxujMC4w
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-password
      namespace: main-application

