apiVersion: v1
kind: Service
metadata:
  name: pingpong-application-loadbalancer-svc
  namespace: main-application
spec:
  type: LoadBalancer # This should be the only unfamiliar part
  selector:
    app: main-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000