apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-password
  namespace: todo-application
spec:
  encryptedData:
    DB_PASSWORD: AgCLtZ2A1GwBvxae0PZJbOFH+PnCY1ibwp429XP7is0UcZq6eirISCcd62SxiUmfdgEH0Hn7vXjHCB6bhjIvkU8pIhUDAhJTUaWuHZHu1NCiZpVksBbNfI1A+EVoxkvqYcdrfGfvCplRTamMKZhJndGxKjRGqWn0Iz5De0FVsYeUcW3Y8zySpyVX+Mc+VYJesuwcFFdQ1MOVaIrjFkEYqJPLRlfjkECi/N5ADgEJeZjzI+drRTDRjybYytznp3yr70rtJfkUBCjKz9AeB+JueAW8Td1UsQ/h0QltAygEu8DTBz0GK8O3MNzhPvEXXA+DqO8nbBGlQjH5YnPAjZwFp8NcaBrXwfq3Umcmo4+ED16MXFYjUvved1jUlw0tafaEiYGxc1jJ/tJnAFLk3SN4AcoXbhRUC3oXG7XDFJgLHCvJ0CpfUDgKRIiDRzDwYLvOib+jFVYOv2wg53sBAYJ6xW6rY0GlHBqeFht/lfP44Iqp61gXUci22Md9f5HkJ8bfoewA6Fy8qWp88QO06gtKFGxc+2Dwxe9TFHTaQFRqN5fiRPQL74fXEwi/TddvkGU5lJNmxrcD+KwgcnYzqJhopBye5WPHrXJb7WG/SRt7wZG1KBxeazI7vZdy/cAcQ2jeb5IxxxItPbrM3ak+MVQIg52BZBFT0AymxhkhJ0tbb6TJWLzLJPqJBzb+yTZXODvgGW1bIzKxZXV18QFdqzi04p8=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-password
      namespace: todo-application

