apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/todoapp-namespace.yaml
- manifests/configmap.yaml
- manifests/deployment-todo-backend.yaml
- manifests/deployment-todo.yaml
- manifests/ingress.yaml
- manifests/postgres-config.yaml
- manifests/postgres-password-sealed-secret.yaml
- manifests/postgres-service.yaml
- manifests/postgres-stateful-set.yaml
- manifests/service-todo-backend.yaml
- manifests/service-todo.yaml
- manifests/analysistemplate.yaml
- manifests/broadcaster-secrets.yaml
- manifests/deployment-broadcaster.yaml
images:
- name: BACK_IMAGE
  newName: niklasku/dev_kub_todolist_backend
  newTag: e419557a26301a327e06dfd6fa6aa89aa9c89355
- name: BROADCASTER_IMAGE
  newName: niklasku/dev_kub_broadcaster
  newTag: e419557a26301a327e06dfd6fa6aa89aa9c89355
- name: FRONT_IMAGE
  newName: niklasku/dev_kub_todolist
  newTag: e419557a26301a327e06dfd6fa6aa89aa9c89355
