apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-password
  namespace: main-application
spec:
  encryptedData:
    DB_PASSWORD: AgBokRXzN6a1ilkbuQ0Wo72W92hxXVDP+Tr2BlPhKyGhQc2wp4USMyTWUQBeH2FQp658UWqOKGQHYju9Oi+PJc1QEVkioN/0xQ4eTbEqgYfBKQD1Tt3xMJM4T5k57yd+6u/icxF8wRatiKVsKsB4pkRdGm9KYpRjN6JLpnyV2rkm+fHNFw20JpoPpNlB/5egOT/Hl1l6jbqnFlfWMaMKV9ll2P4V0D8JlCP1dmkGkApx67oKatIzwqr0OoeZS8GsfJ/8ucV8bgLeo7j3aZeDhdjadxPhKIlAkEfR3CG4d523WzBr360Aasm7caeziPa0JNuIfmUhWMivad1AHIT9xTlIF1g/xUReXfaY8EEoxvdS7S57wS2LLWrskvAyb81RcH6ETvYssEwYD2PPaZ2Aamg2oQH2ZqjL0SVmG0S5U7rWEDoZ1+i4mHDIsgrGsydwvGIIENpZuTgHiuikMbBchQrhLdQFTH55rNfjWPzm047tKGNOy2jCuWwz3UrmxvGLh45XAIwIcdSFaOiWJwNNdC+DQvky2ReFt2UbUSpKh1huK+AMOLgMJC2sBZdkpYVjOpmFiT40kQ+9Na0ktLQW5oA+Jk07XrWmEH52c63RbKPL7sdr2kG8nzqHQLopNZMrKLJxV25X02TAMkDBYpHWtPrFQjGm+w+rYxWnRY6qcSnRdMn9+UCx756Jfiw00ZiUb80uoH0LvMqyOQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-password
      namespace: main-application

