apiVersion: v1
kind: Service
metadata:
  namespace: todo-application
  name: todolist-scv
spec:
  type: ClusterIP
  selector:
    app: todolist
  ports:
    - name: todolist
      port: 2345
      protocol: TCP
      targetPort: 3000