name: Deploy project gitops

on:
  push:
    branches:
      - master
    paths:
      - 'part4/4_8/applications/**'
      - '.github/workflows/gitops-deploy.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build and push
    - name: Publish broadcaster to Registry
      uses: docker/build-push-action@v1
      with:
        repository: niklasku/dev_kub_broadcaster
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: part4/4_8/applications/broadcaster
    - name: Publish frontend to Registry
      uses: docker/build-push-action@v1
      with:
        repository: niklasku/dev_kub_todolist
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: part4/4_8/applications/todoapp
    - name: Publish backend to Registry
      uses: docker/build-push-action@v1
      with:
        repository: niklasku/dev_kub_todolist_backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: part4/4_8/applications/todoapp_backend

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      working-directory: part4/4_8/k8s
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update yamls
      working-directory: part4/4_8/k8s
      run: |-
        ./kustomize edit set image BROADCASTER_IMAGE=niklasku/dev_kub_broadcaster:${{ github.sha }}
        ./kustomize edit set image FRONT_IMAGE=niklasku/dev_kub_todolist:${{ github.sha }}
        ./kustomize edit set image BACK_IMAGE=niklasku/dev_kub_todolist_backend:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: 'part4/4_8/k8s/kustomization.yaml'
        message: New version release for project ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}